name: oj-language-server-dev

services:
  traefik:
    image: traefik:v3.2
    volumes:
      - ./traefik-conf:/traefik-conf
    command: --configFile=/traefik-conf/static.yaml
    ports:
      - 9000:8080

  web:
    build:
      dockerfile: ./web.Dockerfile

  cpp:
    # image: pigeonojdev/oj-language-server-cpp:${TAG:-latest}
    build:
      dockerfile: ./cpp.Dockerfile

  java:
    # image: pigeonojdev/oj-language-server-java:${TAG:-latest}
    build:
      dockerfile: ./java.Dockerfile

  python:
    # image: pigeonojdev/oj-language-server-python:${TAG:-latest}
    build:
      dockerfile: ./python.Dockerfile
